### ISSUE TITLE
Crash on password containing modulo character (%).

### ISSUE THREAD

**Issue by skyghis** [skyghis/j-interop-ng#5]
When connecting to registry to convert program name to program ID, a password decode is executed on a password string not encoded resulting to :

```
java.lang.IllegalArgumentException: URLDecoder: Illegal hex characters in escape (%) pattern - For input string: "w0"
	at java.net.URLDecoder.decode(URLDecoder.java:194)
	at rpc.ncacn_np.RpcTransport.parse(RpcTransport.java:209)
	at rpc.ncacn_np.RpcTransport.<init>(RpcTransport.java:62)
	at rpc.ncacn_np.TransportFactory.createTransport(TransportFactory.java:28)
	at rpc.Stub.attach(Stub.java:108)
	at rpc.Stub.call(Stub.java:113)
	at org.jinterop.winreg.smb.JIWinRegStub.winreg_OpenHKLM(JIWinRegStub.java:88)
	at org.jinterop.dcom.core.JIProgId.getIdFromWinReg(JIProgId.java:126)
	at org.jinterop.dcom.core.JIProgId.getCorrespondingCLSID(JIProgId.java:158)
	at org.jinterop.dcom.core.JIComServer.<init>(JIComServer.java:413)
	at org.jinterop.dcom.test.MSWMI2.<init>(MSWMI2.java:39)
	at org.jinterop.dcom.test.MSWMI2.main(MSWMI2.java:95)
```

Code to reproduce : 

```java
JISession session = JISession.createSession(domain, username, password);
JIProgId id = JIProgId.valueOf("WbemScripting.SWbemLocator");
comStub = new JIComServer(id, address, session); // Crash here
```

**Comment by skyghis** [comment]
Found an asymmetric usage of `URLEncode` / `URLDecode` whth some commented code.
